# Configuration du projet
project_config:
    seed: 42
    running_model: "GGN"

# Configuration de l'ensemble de données
data:
  path: "data/raw/2023_eegpainmarkers_laval/"  # Chemin vers le fichier de données
  subjects: ["sub-002", "sub-003"] #["sub-002", "sub-003", "sub-004", "sub-005", "sub-006", "sub-007", "sub-008", "sub-009", "sub-010", "sub-011", "sub-012", "sub-013", "sub-014", "sub-015", "sub-016", "sub-017", "sub-019", "sub-021", "sub-022", "sub-023", "sub-024", "sub-025", "sub-026", "sub-027", "sub-028", "sub-030", "sub-031", "sub-032", "sub-033", "sub-034", "sub-035", "sub-037", "sub-038"]
  tasks: ["audioactive", "audiopassive", "thermalactive", "thermalpassive"]
  sampling_rate: 256                       # Fréquence d'échantillonnage en Hz
  preprocessing:
    filter:
      type: "bandpass"                     # Type de filtre (bandpass, lowpass, highpass)
      low_freq: 1                          # Fréquence de coupure basse en Hz
      high_freq: 40                        # Fréquence de coupure haute en Hz
    normalization: true                    # Normalisation des données (true/false)
  train_test_split:
    test_size: 0.20                         # Pourcentage de données pour le test
    validation_size: 0.10
    random_seed: 42                        # Graine pour la reproductibilité
    random_state: 42

# Configuration des modèles
models:
  SVM:
    parameters:
      kernel: "linear"
      C: 1.0
      gamma: "scale"
  GGN:
    parameters:
      in_channels: 64
      hidden_channels: 128
      out_channels: 2

# Sauvegarde et logs
output:
  model_save_path: "models/trained"         # Chemin pour sauvegarder les modèles
  logs_path: "logs/"                       # Chemin pour les logs d'entraînement
  save_best_model: true                    # Sauvegarder le meilleur modèle uniquement
  processed_data_save_path: "data/processed"
  split_data_save_path: "data/split"
  results_save_path: "results/"
